const C=window.ROADMAP_CONFIG||{};let D=null,SHA=null,dirty=false;
const $=id=>document.getElementById(id);const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
const api=()=>`https://api.github.com/repos/${C.githubOwner}/${C.githubRepo}/contents/${C.roadmapPath||"roadmap.json"}?ref=${C.githubBranch||"main"}`;
function msg(t,ok=true){const e=$("message");e.textContent=t;e.className=`message show ${ok?"ok":"bad"}`;setTimeout(()=>e.classList.remove("show"),5000)}
function token(){return sessionStorage.getItem("bhGithubToken")||""}
function headers(auth=true){const h={"Accept":"application/vnd.github+json","X-GitHub-Api-Version":"2022-11-28"};if(auth&&token())h.Authorization=`Bearer ${token()}`;return h}
function utf8ToBase64(s){const bytes=new TextEncoder().encode(s);let bin="";bytes.forEach(b=>bin+=String.fromCharCode(b));return btoa(bin)}
function base64ToUtf8(s){const bin=atob(s.replace(/\n/g,""));const bytes=Uint8Array.from(bin,c=>c.charCodeAt(0));return new TextDecoder().decode(bytes)}
function mark(){dirty=true;$("saveState").textContent="Ungespeicherte Änderungen vorhanden."}
function syncProject(){D.project.version=$("version").value;D.project.updated=$("updated").value;D.project.summary=$("summary").value}
function statusChanged(i,v){D.items[i].status=v;if(v==="done")D.items[i].progress=100;if(v==="planned"&&D.items[i].progress===100)D.items[i].progress=0;D.items[i].updated=D.project.updated;renderTasks();mark()}
function render(){
 $("version").value=D.project.version;$("updated").value=D.project.updated;$("summary").value=D.project.summary;renderTasks();renderMilestones();renderChanges();
 document.querySelectorAll("#version,#updated,#summary").forEach(e=>e.oninput=()=>{syncProject();mark()})
}
function taskFields(x,i){return `<div class="form-grid"><label class="field wide">Titel<input value="${esc(x.title)}" oninput="D.items[${i}].title=this.value;mark()"></label><label class="field wide">Beschreibung<textarea oninput="D.items[${i}].description=this.value;mark()">${esc(x.description)}</textarea></label><label class="field">Status<select onchange="statusChanged(${i},this.value)"><option value="planned" ${x.status==="planned"?"selected":""}>Geplant</option><option value="in_progress" ${x.status==="in_progress"?"selected":""}>In Arbeit</option><option value="done" ${x.status==="done"?"selected":""}>Erledigt</option></select></label><label class="field">Fortschritt in %<input type="number" min="0" max="100" value="${x.progress}" oninput="D.items[${i}].progress=Math.max(0,Math.min(100,Number(this.value)));if(D.items[${i}].progress===100)D.items[${i}].status='done';else if(D.items[${i}].status==='done')D.items[${i}].status='in_progress';mark()"></label><label class="field">Bereich<input value="${esc(x.area)}" oninput="D.items[${i}].area=this.value;mark()"></label><label class="field">Priorität<select onchange="D.items[${i}].priority=this.value;mark()"><option value="high" ${x.priority==="high"?"selected":""}>Hoch</option><option value="medium" ${x.priority==="medium"?"selected":""}>Mittel</option><option value="normal" ${x.priority==="normal"?"selected":""}>Normal</option></select></label><label class="field">Verantwortlich<input value="${esc(x.owner)}" oninput="D.items[${i}].owner=this.value;mark()"></label><label class="field">Aktualisiert<input value="${esc(x.updated)}" oninput="D.items[${i}].updated=this.value;mark()"></label></div><div class="row-actions"><button class="btn secondary danger" onclick="removeTask(${i})">Aufgabe löschen</button></div>`}
function renderTasks(){$("tasks").innerHTML=D.items.map((x,i)=>`<details class="edit"><summary><strong>${esc(x.title)}</strong><span class="pill ${x.status}">${x.progress}% · ${x.status==="done"?"Erledigt":x.status==="in_progress"?"In Arbeit":"Geplant"}</span></summary><div class="edit-body">${taskFields(x,i)}</div></details>`).join("")}
function renderMilestones(){$("milestones").innerHTML=D.milestones.map((m,i)=>`<details class="edit"><summary><strong>${esc(m.title)}</strong><span class="pill">${m.taskIds.length} Aufgaben</span></summary><div class="edit-body"><div class="form-grid"><label class="field wide">Titel<input value="${esc(m.title)}" oninput="D.milestones[${i}].title=this.value;mark()"></label><label class="field wide">Beschreibung<textarea oninput="D.milestones[${i}].description=this.value;mark()">${esc(m.description)}</textarea></label><label class="field wide">Zugeordnete Aufgaben${D.items.map(t=>`<span style="display:flex;gap:8px;align-items:center;margin-top:8px;font-weight:400"><input style="width:auto;height:auto" type="checkbox" ${m.taskIds.includes(t.id)?"checked":""} onchange="toggleMilestoneTask(${i},'${t.id}',this.checked)"> ${esc(t.title)}</span>`).join("")}</label></div><button class="btn secondary danger" onclick="removeMilestone(${i})">Meilenstein löschen</button></div></details>`).join("")}
function renderChanges(){$("changes").innerHTML=D.changelog.map((x,i)=>`<details class="edit"><summary><strong>${esc(x.title)}</strong><span class="pill">${esc(x.date)}</span></summary><div class="edit-body"><div class="form-grid"><label class="field">Datum<input value="${esc(x.date)}" oninput="D.changelog[${i}].date=this.value;mark()"></label><label class="field">Titel<input value="${esc(x.title)}" oninput="D.changelog[${i}].title=this.value;mark()"></label><label class="field wide">Beschreibung<textarea oninput="D.changelog[${i}].text=this.value;mark()">${esc(x.text)}</textarea></label></div><button class="btn secondary danger" onclick="removeChange(${i})">Eintrag löschen</button></div></details>`).join("")}
function removeTask(i){if(confirm("Aufgabe wirklich löschen?")){const id=D.items[i].id;D.items.splice(i,1);D.milestones.forEach(m=>m.taskIds=m.taskIds.filter(x=>x!==id));renderTasks();renderMilestones();mark()}}
function removeMilestone(i){if(confirm("Meilenstein wirklich löschen?")){D.milestones.splice(i,1);renderMilestones();mark()}}
function removeChange(i){if(confirm("Eintrag wirklich löschen?")){D.changelog.splice(i,1);renderChanges();mark()}}
function toggleMilestoneTask(i,id,on){const a=D.milestones[i].taskIds;if(on&&!a.includes(id))a.push(id);if(!on)D.milestones[i].taskIds=a.filter(x=>x!==id);mark()}
$("addTask").onclick=()=>{const id=`task-${Date.now()}`;D.items.push({id,title:"Neue Aufgabe",description:"Beschreibung ergänzen",area:"Allgemein",priority:"normal",status:"planned",progress:0,owner:"Jeremy",updated:D.project.updated});renderTasks();renderMilestones();mark()};
$("addMilestone").onclick=()=>{D.milestones.push({id:`milestone-${Date.now()}`,title:"Neuer Meilenstein",description:"Beschreibung ergänzen",taskIds:[]});renderMilestones();mark()};
$("addChange").onclick=()=>{D.changelog.unshift({date:D.project.updated,title:"Neue Änderung",text:"Beschreibung ergänzen"});renderChanges();mark()};
async function load(useApi=false){try{if(useApi||token()){const r=await fetch(`${api()}&_=${Date.now()}`,{headers:headers(),cache:"no-store"});if(!r.ok)throw new Error(`${r.status} ${await r.text()}`);const j=await r.json();SHA=j.sha;D=JSON.parse(base64ToUtf8(j.content));$("connection").classList.add("connected");$("connection").querySelector("span:last-child").textContent="Mit GitHub verbunden"}else{const r=await fetch("roadmap.json",{cache:"no-store"});D=await r.json()}render();dirty=false;$("saveState").textContent="Roadmap geladen."}catch(e){msg("Laden fehlgeschlagen: "+e.message,false)}}
$("connect").onclick=async()=>{const t=$("token").value.trim();if(!t)return msg("Token eingeben.",false);sessionStorage.setItem("bhGithubToken",t);$("token").value="";await load(true)};
$("reload").onclick=()=>{if(!dirty||confirm("Ungespeicherte Änderungen verwerfen?"))load(Boolean(token()))};
$("save").onclick=async()=>{if(!token())return msg("Zuerst mit GitHub verbinden.",false);syncProject();try{$("save").disabled=true;$("save").textContent="Speichert …";const fresh=await fetch(`${api()}&_=${Date.now()}`,{headers:headers(),cache:"no-store"});if(!fresh.ok)throw new Error("Aktuelle Dateiversion konnte nicht geladen werden.");const meta=await fresh.json();const body={message:`roadmap: Stand ${D.project.updated} aktualisieren`,content:utf8ToBase64(JSON.stringify(D,null,2)),sha:meta.sha,branch:C.githubBranch||"main"};const r=await fetch(`https://api.github.com/repos/${C.githubOwner}/${C.githubRepo}/contents/${C.roadmapPath||"roadmap.json"}`,{method:"PUT",headers:{...headers(),"Content-Type":"application/json"},body:JSON.stringify(body)});if(!r.ok)throw new Error(`${r.status}: ${await r.text()}`);const j=await r.json();SHA=j.content.sha;dirty=false;$("saveState").textContent="Gespeichert. GitHub Pages aktualisiert sich automatisch.";msg("Roadmap wurde erfolgreich direkt in GitHub gespeichert.")}catch(e){msg("Speichern fehlgeschlagen: "+e.message,false)}finally{$("save").disabled=false;$("save").textContent="Direkt in GitHub speichern"}};
window.addEventListener("beforeunload",e=>{if(dirty){e.preventDefault();e.returnValue=""}});load(false);